name: "Checkout test"
on: [workflow_dispatch]
jobs:
  pycheckout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: "Checkout pycoalprocessing"
      with:
        repository: "pyanodon/pycoalprocessing"
        path: "pycoalprocessing"
    - uses: actions/checkout@master
      name: "Checkout pycoalprocessinggraphics"
      with:
        repository: "pyanodon/pycoalprocessinggraphics"
        path: "pycoalprocessinggraphics" 