on:
  workflow_dispatch:
  pull_request:
  pull_request_target:
  push: 

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  two:
    runs-on: ubuntu-latest
    needs: [one]
    steps:
      - name: Dump Needs context
        env:
          GITHUB_CONTEXT: ${{ toJSON(needs) }}
        run: echo "$GITHUB_CONTEXT"
  three:
    runs-on: ubuntu-latest
    outputs:
      num: ${{ steps.test.outputs.num }}
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - name: set-env
        env:
          VAR_VERSION: ${{ matrix.version }}
      - name: matrix-test
        run: |
          echo "$VAR_VERSION"
          if [ "$VAR_VERSION" = "12" ]; then exit 1; fi
      - id: test
        if: ${{ job.status == 'failure' }}
        run: echo "::set-output name=num::$VAR_VERSION"        
  four:
    runs-on: ubuntu-latest
    needs: [three]
    if: ${{ always() }}
    steps:
      - name: Dump Needs context
        env:
          GITHUB_CONTEXT: ${{ toJSON(needs) }}
          MATRIX_RESULT: ${{ (needs.one.result == 'success') && needs.three.result || needs.one.result }}
        run: |
          echo "$GITHUB_CONTEXT" 
          echo "$MATRIX_RESULT"
  five:
    runs-on: ubuntu-latest
    needs: [one, two, three, four]
    if: always()
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
          
