on:
  workflow_dispatch:
  pull_request:
  pull_request_target:
  push: 

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  two:
    runs-on: ubuntu-latest
    needs: [one]
    steps:
      - name: Dump Needs context
        env:
          GITHUB_CONTEXT: ${{ toJSON(needs) }}
        run: echo "$GITHUB_CONTEXT"
  three:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - name: matrix-test
        env:
          VAR_VERSION: ${{ matrix.version }}
        run: |
          echo "$VAR_VERSION"
          if [ "$VAR_VERSION" = "12" ]; then exit 1; fi
  four:
    runs-on: ubuntu-latest
    needs: [three]
    if: ${{ always() }}
    steps:
      - name: Dump Needs context
        env:
          GITHUB_CONTEXT: ${{ toJSON(needs) }}
          MATRIX_RESULT: ${{ needs.three.result }}
        run: |
          echo "$GITHUB_CONTEXT" 
          echo "$MATRIX_RESULT"
