name: "Docker test"

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Factorio action test
    steps:
      - name: Factorio docker test
        id: factorio
        uses: ShadowGlass0/factorio-docker-for-github-actions@main
