name: "Reuse test"

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.TEST_SECRET }}
      - uses: actions/checkout@master
        name: "Checkout pycoalprocessinggraphics"
        with:
          repository: "pyanodon/pycoalprocessinggraphics"
          path: "mods/pycoalprocessinggraphics" 
          token: ${{ secrets.SHADOWGLASS_PAT }}
