name: "TAGIT test"

on: 
  workflow_dispatch:  

jobs:
  tagit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fischerscode/tagger@v0.1
        with:
          prefix: v
          tag: v1.0.0
          