name: "TAGIT test"

on: 
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  tagit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fischerscode/tagger@v0.1
        with:
          prefix: v
          tag: ${{ github.ref_name }}
